version: '3.8'

services: 
    api:
      build: ./packages/api
      ports:
      - "3001:3333"
    web:
      depends_on:
        - api
      build: ./packages/web
      ports:
      - "3000:3000"

networks:
  web:
  api: